#!/usr/bin/zsh

#
# azsphere-docker-aliases-set
#
# Create aliases for the mcr.microsoft.com/azurespheresdk image executables
#

alias azsphere-docker-default='docker run --rm -v $PWD:/home/azsphereuser liydu/azsphere-docker-devcontainer'

# Alias for CMake build
alias azsphere-cmake='azsphere-docker-default cmake -G "Ninja" \
    -DCMAKE_TOOLCHAIN_FILE="/opt/azurespheresdk/CMakeFiles/AzureSphereToolchain.cmake" \
    -DAZURE_SPHERE_TARGET_API_SET="latest-lts" \
    -DCMAKE_BUILD_TYPE="Debug"'
alias azsphere-ninja='azsphere-docker-default ninja'

# Alias for the iteractive container
alias azsphere-docker-interactive='docker run --rm -v $PWD:/home/azsphereuser -it liydu/azsphere-docker-devcontainer'