#!/usr/bin/zsh

#
# azsphere-docker-aliases-set
#
# Create aliases for the mcr.microsoft.com/azurespheresdk image executables
#

unalias azsphere-docker-default     2>/dev/null

# Aliases for CMake build
unalias azsphere-cmake           2>/dev/null
unalias azsphere-ninja           2>/dev/null

unalias azsphere-docker-interactive 2>/dev/null